/* This file is generated by Ziggy. */
declare module 'ziggy-js' {
  interface RouteList {
    "sanctum.csrf-cookie": [],
    "ignition.healthCheck": [],
    "ignition.executeSolution": [],
    "ignition.updateConfig": [],
    "login": [],
    "companies.index": [],
    "companies.show": [
        {
            "name": "company",
            "binding": "id"
        }
    ],
    "companies.store": [],
    "companies.update": [
        {
            "name": "company",
            "binding": "id"
        }
    ],
    "companies.export": [],
    "branches.index": [],
    "branches.show": [
        {
            "name": "branch",
            "binding": "id"
        }
    ],
    "branches.store": [],
    "branches.update": [
        {
            "name": "branch",
            "binding": "id"
        }
    ],
    "branches.export": [],
    "departments.index": [],
    "departments.show": [
        {
            "name": "department",
            "binding": "id"
        }
    ],
    "departments.store": [],
    "departments.update": [
        {
            "name": "department",
            "binding": "id"
        }
    ],
    "departments.export": [],
    "jobs.index": [],
    "jobs.show": [
        {
            "name": "job",
            "binding": "id"
        }
    ],
    "jobs.store": [],
    "jobs.update": [
        {
            "name": "job",
            "binding": "id"
        }
    ],
    "jobs.export": [],
    "employees.index": [],
    "employees.show": [
        {
            "name": "employee",
            "binding": "id"
        }
    ],
    "employees.store": [],
    "employees.update": [
        {
            "name": "employee",
            "binding": "id"
        }
    ],
    "employees.export": [],
    "contract_types.index": [],
    "contract_types.show": [
        {
            "name": "contract_type",
            "binding": "id"
        }
    ],
    "contract_types.store": [],
    "contract_types.update": [
        {
            "name": "contract_type",
            "binding": "id"
        }
    ],
    "contract_types.export": [],
    "contracts.index": [],
    "contracts.show": [
        {
            "name": "contract",
            "binding": "id"
        }
    ],
    "contracts.store": [],
    "contracts.update": [
        {
            "name": "contract",
            "binding": "id"
        }
    ],
    "contracts.export": [],
    "asset_categories.index": [],
    "asset_categories.show": [
        {
            "name": "asset_category",
            "binding": "id"
        }
    ],
    "asset_categories.store": [],
    "asset_categories.update": [
        {
            "name": "asset_category",
            "binding": "id"
        }
    ],
    "asset_categories.export": [],
    "asset_types.index": [],
    "asset_types.show": [
        {
            "name": "asset_type",
            "binding": "id"
        }
    ],
    "asset_types.store": [],
    "asset_types.update": [
        {
            "name": "asset_type",
            "binding": "id"
        }
    ],
    "asset_types.export": [],
    "vendors.index": [],
    "vendors.show": [
        {
            "name": "vendor",
            "binding": "id"
        }
    ],
    "vendors.store": [],
    "vendors.update": [
        {
            "name": "vendor",
            "binding": "id"
        }
    ],
    "vendors.export": [],
    "products.index": [],
    "products.show": [
        {
            "name": "product"
        }
    ],
    "products.store": [],
    "products.update": [
        {
            "name": "product"
        }
    ],
    "products.export": []
}
}
export {};
